export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const GET_TEACHERS = 'GET_TEACHERS';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_FEEDBACK_FORM = 'GET_FEEDBACK_FORM';

export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const FEEDBACK_FORM_LOADING = 'FEEDBACK_FORM_LOADING';



